spring:
  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    host: smtp.naver.com
    username: ${MAIL_ID}
    password: ${MAIL_PASSWORD}
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.naver.com
        debug: true

  application:
    name: shop_sparta

  datasource:
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    url: jdbc:mysql://localhost:3307/shop

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
  level:
    root: INFO


server:
  port: ${SERVER_PORT}
