spring:
  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      #host: ${REDIS_HOST}
      host: localhost
      #port: ${REDIS_PORT}
      port: 6379

  mail:
    host: smtp.naver.com
    #username: ${MAIL_ID}
    #password: ${MAIL_PASSWORD}
    username: sin9158
    password: 1234
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.naver.com
        debug: true

  application:
    name: shop_sparta

  datasource:
    #password: ${DATASOURCE_PASSWORD}
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: ${DATASOURCE_USERNAME}
    username: root
    url: jdbc:mysql://localhost:3307/shop

  jpa:
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
  level:
    root: INFO


server:
  #port: ${SERVER_PORT}
  port: 8080

