name: Run Test

# develop branch가 push되거나 pull request 하면 테스트 실행
on:
  push:
    branches: [ develop ]
  pull_request:
    branches:
      - develop

jobs:
  build:
    # 운영체제 설정, ubuntu latest보단 서버와 버전을 맞추는 게 좋을듯?
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run tests in Docker container
        working-directory: ${{ github.workspace }}
        run: docker-compose run --rm spring-app ./gradlew clean test
